### ISSUE TITLE
Document creating the admin user

### ISSUE THREAD

**Issue by jerrykan** [jerrykan/gogs-formula#1]
Currently there is no real way to automate the creation of the initial admin user in Gogs. Some documentation should be added to the README about the options available for creating the admin user after salt has installed Gogs.

**Comment by sofixa** [comment]
Indeed, it would be a good idea to document this. 

I just installed Gogs via your formula, and i have the login page, but have no idea what the admin user/password are.

**Comment by sofixa** [comment]
From what i gather, the INSTALL_LOCK variable in app.ini should be set to False so post-install you can setup and configure the admin user?

**Comment by jerrykan** [comment]
@sofixa yeah pretty much. The following is a full list of steps you can follow:

* set the gogs config directory to be world writable so the installer can write to it:
```
chmod 777 /etc/gogs/
```
* edit the /etc/gogs/app.ini file to enable the installer:
```
30c30
< INSTALL_LOCK = true
---
> INSTALL_LOCK = false
```
* browse to `http://<hostname>/install` to run the installer and set up an admin account.
* reset the gogs config directory to correct permissions:
```
chmod 755 /etc/gogs/
```
* run salt again to reconfigure the /etc/gogs/app.ini file:
```
salt-call state.apply --output-diff
```

Now I think about it the formula should probably handle re-setting the correct directory permissions. I'll have a look at fixing that up.

----

Alternatively you could manually create the admin user by inserting a new row in the `user` table in the database. Some details on this can be found in the following puppet gogs modules:
* https://github.com/Siteminds/puppet-gogs#special-notes

**Comment by jerrykan** [comment]
Documented in 1e92f456
